services:
  - type: web
    name: dukaandhar
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/run_server.py
    envVars:
      - key: PORT
        value: 10000
